name: Linter

on: [pull_request]

jobs:
  tests:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm i
      - name: eslint
        # This is the name of the author of the github action.
        # cspell:ignore reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
