name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - run: npm run test:coverage
        name: Run test with coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/cobertura-coverage.xml
