name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn test:coverage
        name: Run test with coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          # This is the name of the coverage reporter.
          # cspell:ignore cobertura
          files: ./src/coverage/cobertura-coverage.xml
